config/routes.rb
Rails.application.routes.draw do
  root 'rants#index'

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-out' => 'registrations#destroy', as: :signout
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/search' => 'rants#index', as: :search

  # using authentication or sessions controller for sign-in

  resources :users
  resources :rants

end

app/models/rant.rb
class Rant < ActiveRecord::Base
  belongs_to :user

  validates_length_of :body, :minimum => 144, :allow_blank => :false
  validates :title, presence: true
  validates :body, presence: true

  def self.search(search)
    where("body ILIKE ? or title ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_secure_password

  has_many :rants

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    User.find_by(id: session[:user_id])
    # User.find(session[:user_id])
  end

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  # def new
  #   @user = User.new
  # end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to rants_path
    else
      redirect_to signin_path, notice: 'Username / password combination is invalid'
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/rants_controller.rb
class RantsController < ApplicationController

  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @rants = Rant.all
    @rants = Rant.search(params[:search])
    # if @rants.count < 1
    #   flash[:notice] = "These are not the droids you are looking for."
    #   render :index
    # end
  end

  def new
    if current_user
      @rant = Rant.new
    else
      redirect_to rants_path, notice: 'You must log in!'
    end
  end

  def create
    # Lines 9-12 different versions of lines 15 & 16:
    # @user = current_user
    # @rant = @user.rants.new(rant_params)

    # @rant = current_user.rants.new(rant_params)

    @rant = Rant.new(rant_params)
    @rant.user_id = current_user.id  # set the rant to the current_user
    if @rant.save
      redirect_to rants_path, notice: "Rant created"
    else
      render :new, notice: "You've gotta say more than that!"
    end
  end

  def edit
    @rant = Rant.find(params[:id])
    render :edit
  end

  def update
    @rant = Rant.find(params[:id])
    if @rant.update(rant_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @rant = Rant.find(params[:id])
    @rant.destroy
    redirect_to root_path
  end

  private

  def rant_params
    params.require(:rant).permit(:title, :body, :user_id)
  end

  def correct_user
    @rant = current_user.rants.find_by(id: params[:id])
    redirect_to root_path, notice: "Not authorized to edit this rant" if @rant.nil?
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thanks for signing up for Rantly!"
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @rants = @user.rants.all.order('created_at DESC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<div class="container">
  <div class="profile-box"><br>
    <%= form_tag @user, url: signin_path do |f| %>
    <div class="has-feedback">
      <%= email_field_tag :email, nil, class:"user-form", placeholder: "Your email" %>
      <i class="fa fa-user form-control-feedback"></i>
    </div>

    <div class="has-feedback">
      <%= password_field_tag :password, nil, class:"user-form", placeholder: "Your password" %>
      <i class="fa fa-lock form-control-feedback"></i>
    </div>

    <div class="form-group">
      <%= submit_tag "Log In", class: "profile-button" %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rantly</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:400,900|Laila:700|Hind:200' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>

  <div class= "navbar">
    <div class="container">
      <%=link_to "Rantly", root_path %></a>
        <span><%= link_to "Rants", root_path %></span>
        <span><%= link_to "Users", users_path %></span>
        <span><%= link_to "Sign Up", signup_path %></span>

        <span><%= link_to "Sign In", signin_path %>

        <% if current_user %>
        <span class = "pull-right"><%= current_user.first_name %></span>
        <span><%= link_to "Sign out", signout_path %></span>
        <% end %>
    </div>
  </div>

    <!-- <%= form_tag("/search", method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q, nil, :placeholder => "Search") %>
    <%= submit_tag("Search") %>
    <% end %> -->

  <div class="header">
    <div class="container">

       <%= form_tag search_path, class:"search", :method => 'get' do %>
       <% if params[:search] == "" %>
           <%= text_field_tag :search, params[:search], placeholder: "This can't be blank!", class: "search" %>
       <% else %>
         <%= text_field_tag :search, params[:search], placeholder: "Search", class: "search" %>
       <% end %>
         <!-- <%= submit_tag "Search", :name => nil, class: "btn btn-warning" %> -->
       <% end %>
       <%= link_to "New Rant", new_rant_path, class: "new-button" %>
    </div>
  </div>

  <div class="rcontainer">
    <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <span class="scroll"><%= yield %></span>
  </div>

</body>
</html>

app/views/rants/edit.html.erb
<% if @rant.errors.any? %>
<% @rant.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>

<% if @rant.user == current_user %>
  <div class="rant-box">
    <%= form_for [@user, @rant] do |f| %>
      <div class = "rant-head">
        <h2><%= f.text_field :title, class: "wide" %></h2>
        <%= link_to "Delete", rant_path(@rant), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to " Cancel", rants_path %>
        <%= f.submit "Save" %>
      </div>

    <div class= "rant-post">
      <div class="avatar">
    </div>
      <%= f.text_area :body, class:"text-area message" %>
      <div class="countdown"></div>
      </div>
      
    <% end %>
  </div>
<% end %>

app/views/rants/index.html.erb
<div class="scroll">

  <% if @rants.count > 0 %>

    <% @rants.reverse_each do |rant| %>

      <div class="rant-box">
        <div class="rant-head">

          <% if current_user %>
          <% if current_user.id == rant.user_id %>
          <!-- <% if rant.user == current_user %> -->
          <%= link_to "Edit", edit_rant_path(rant) %><br><br>
          <% end %>
          <% end %>
    <% end %>

          <h2><%= link_to rant.title, rant_path(rant) %></h2><br>
        </div>

        <div class="avatar">
        </div>

      <div class="rant-post">
        <%= rant.body %><br><br>
        <%= rant.created_at.strftime "%m-%d-%y" %><br><br>
      </div>
    </div>
  <% end %>

  <% else %>
    <div class="empty-result">
        <h2>These are not the droids you're looking for</h2>
    </div>
  <% end %>

</div>

app/views/rants/new.html.erb
<% if @rant.errors.any? %>
<% @rant.errors.full_messages.each do |message| %>
<%= message %>
<% end %>
<% end %>


<div class="rant-box">
  <%= form_for @rant do |f| %>
    <div class="rant-head">
      <%= link_to "Cancel", rants_path, class: 'btn btn-default btn-sm' %>
      <%= f.submit "Save" %>
      <h2><%= f.text_field :title, class: "wide", :placeholder => "Rant Title" %></h2>
    </div>

    <div class="rant-post">
      <div class="avatar">
      </div>
      <%= f.text_area :body, class:"text-area message", :placeholder => "Start your rant." %>
        <div class="countdown"></div>
      <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="scroll">
  <div class="row">
    <% @users.reverse_each do |user| %>
      <div class="user-tile">
        <div>
          <%= link_to user.full_name, user_path(user) %><br>
          <span><%= user.email %></span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="scroll">
  <% @rants.reverse_each do |rant| %>
    <div class="rant-box">
      <div class="rant-head">
        <% if rant.user == current_user %>
        <%= link_to "Edit", edit_rant_path(rant), class: "body-button fa fa-edit" %>
        <% end %>
        <h2><%= link_to rant.title, rant_path(rant) %></h2><br>
      </div>
      <div class="rant-post">
        <%= rant.body %><br><br>
      </div>
        <%= rant.created_at %><br><br>
    </div>
  <% end %>
</div>